package cz.bezcisobe.backend.util;

import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

/**
 * Test class to validate BCrypt hashes used in Flyway migration V3__seed_users_and_races.sql
 *
 * This test verifies whether the hashes in the migration file will correctly authenticate users.
 * If this test fails, it means the hashes in the migration file are invalid and need to be regenerated.
 *
 * To generate new valid hashes:
 * 1. Visit https://bcrypt-generator.com/
 * 2. Enter the password and set cost factor to 10
 * 3. Copy the generated hash
 * 4. Replace the hash in V3__seed_users_and_races.sql
 */
public class BCryptHashValidationTest {

    private final BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();

    @Test
    void validateAdmin123Hash() {
        String password = "admin123";
        String hash = "$2a$10$mGsI68a2foSCV/fW.wX4Verb4vYuedKEcx8pcddqKwsHgroCiaD96";

        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches(password, hash),
            "Seed hash for 'admin' must verify against BCryptPasswordEncoder"
        );
    }

    @Test
    void validatePassword123Hash() {
        String password = "password123";
        String hash = "$2a$10$XovRDfRfVvmgiXd1rXL7bOTRi/m6KPVmNitbnyUoR97tq8hXh5xfy";

        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches(password, hash),
            "Seed hash for 'jana.novakova' must verify against BCryptPasswordEncoder"
        );
    }

    @Test
    void validateIvka123Hash() {
        String password = "ivka123";
        String hash = "$2a$10$4zCsCZ29WwEFxJr6/1DmEeWR.pMMRDzb4ixRtF15u3QPE5W4Gku.y";

        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches(password, hash),
            "Seed hash for 'ivka' must verify against BCryptPasswordEncoder"
        );
    }

    @Test
    void generateNewHashes() {
        String[] passwords = {"admin123", "password123", "ivka123"};

        System.out.println("\n=== Generating new BCrypt hashes (cost factor 10) ===\n");
        for (String password : passwords) {
            String hash = encoder.encode(password);
            System.out.println("Password: " + password);
            System.out.println("Hash:     " + hash);
            System.out.println();
        }
        System.out.println("Use these hashes to update V3__seed_users_and_races.sql");
    }

    // ---- V5 seed users (generated by backend/scripts/build_seed_sql.py) ----

    @Test
    void validate_petr_svoboda_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("heslo2026", "$2b$10$YTr8Q/U9DFaYpjORTdGZIepDHpC8Q95NL5diVy62n/28i3lFhQE8y"),
            "V5 seed hash for petr.svoboda must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_martina_dvorakova_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("runner2026", "$2b$10$luvFdgZ1UFR//Y1/ObcdcuNZDjfWUr5xNbrS/MUSEW6z0Vtbb6kO6"),
            "V5 seed hash for martina.dvorakova must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_tomas_cerny_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("sportak42", "$2b$10$seKGfy3oSwtI7spsXndKduIvrwTOM9OhF0s6Dm5S0cdfvsbpKilES"),
            "V5 seed hash for tomas.cerny must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_katerina_prochazkova_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("bezec2026", "$2b$10$.U0H5SxUHlhYMa/e46/z/eG32H93Kf9h4ArsR3qXx2e1xcZe4Vo72"),
            "V5 seed hash for katerina.prochazkova must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_jakub_kucera_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("kucera2026", "$2b$10$7WlbubMmEgPN9Jo8KBw8UuGqSVNtCvymk0ygMQ0zZ6K7BoZVbomzS"),
            "V5 seed hash for jakub.kucera must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_lucie_vesela_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("lucie2026", "$2b$10$F.GRV0dt1lY.AlS7wfkR7.DhkkDxSOIn6cWHZrdJrYY/bauuc9CQy"),
            "V5 seed hash for lucie.vesela must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_david_horak_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("horak2026", "$2b$10$5kqHAK3lojbhBY3wkkwxaOwH0heOl.H6ooAJxhO3AZeELIviBQvqG"),
            "V5 seed hash for david.horak must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_eva_benesova_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("benesova26", "$2b$10$rmmcYm5YEZCFjobsjNwIv.WyGDurKpdYGXVLsONIa8j3Hp3oe5iO."),
            "V5 seed hash for eva.benesova must verify against BCryptPasswordEncoder");
    }

    // ---- V9 international seed users (generated by build_v9.py) ----

    @Test
    void validate_anna_mueller_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("mueller2026", "$2b$10$OnAq6NE..lgR9FhZVGgoM.2BD5.mk5vgCNx.DkLz.f/hY/MerhogO"),
            "V9 seed hash for anna.mueller must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_carlos_garcia_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("garcia2026", "$2b$10$4BnN9A1vroDMTuf8DUv8IeFDN3AcM27qQ/uLTgrCDfK.45rl5u.La"),
            "V9 seed hash for carlos.garcia must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_marco_rossi_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("rossi2026", "$2b$10$inkzn2dvpUcKZqmGNTT9e.Y3YUIPkiUn3V5uFEYt0JvLK62ByfnY6"),
            "V9 seed hash for marco.rossi must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_philippe_moreau_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("moreau2026", "$2b$10$tRqan2CQvHRU0Hbc5nhSpOwTcBRqh55CveiYng5jAOJtckpz/LwP."),
            "V9 seed hash for philippe.moreau must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_liam_oconnor_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("oconnor26", "$2b$10$5pm15VlDuI6ikkQ4pMQH0eHlTSZzT8idyPTQ2Wynia8CTUo9aCuaW"),
            "V9 seed hash for liam.oconnor must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_sophie_schneider_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("sophie2026", "$2b$10$z1jPXoW1Ye6W45K6HAMxguUZWrgEfmq.3doSSASHf62r4t8IdvqjG"),
            "V9 seed hash for sophie.schneider must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_agnieszka_nowak_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("nowak2026", "$2b$10$yUhCVmbaptTFEsVXpy.Tvu96fYKVktTPy9/G.jyZD6zUlNo07xjFC"),
            "V9 seed hash for agnieszka.nowak must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_erik_andersson_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("erik2026", "$2b$10$/Af2BZc20aREz1dk2aiTneCy/YB/Zax8SVqbX8fkcC1x0nDfnDWMS"),
            "V9 seed hash for erik.andersson must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_maria_silva_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("silva2026", "$2b$10$yH0Ly9Gm1Nshcetgmb1w..i88S6mT5HiNg0RgjCms2ukFNaygJkaC"),
            "V9 seed hash for maria.silva must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_mark_johnson_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("mark2026", "$2b$10$t0bNnG9adEXesOR.0p1UiOEMw1Kkt89z7m6uMU7yn.nTY7Lyph9c6"),
            "V9 seed hash for mark.johnson must verify against BCryptPasswordEncoder");
    }
}
