package cz.bezcisobe.backend.util;

import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

/**
 * Test class to validate BCrypt hashes used in Flyway migration V3__seed_users_and_races.sql
 *
 * This test verifies whether the hashes in the migration file will correctly authenticate users.
 * If this test fails, it means the hashes in the migration file are invalid and need to be regenerated.
 *
 * To generate new valid hashes:
 * 1. Visit https://bcrypt-generator.com/
 * 2. Enter the password and set cost factor to 10
 * 3. Copy the generated hash
 * 4. Replace the hash in V3__seed_users_and_races.sql
 */
public class BCryptHashValidationTest {

    private final BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();

    @Test
    void validateAdmin123Hash() {
        String password = "admin123";
        String hash = "$2a$10$mGsI68a2foSCV/fW.wX4Verb4vYuedKEcx8pcddqKwsHgroCiaD96";

        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches(password, hash),
            "Seed hash for 'admin' must verify against BCryptPasswordEncoder"
        );
    }

    @Test
    void validatePassword123Hash() {
        String password = "password123";
        String hash = "$2a$10$XovRDfRfVvmgiXd1rXL7bOTRi/m6KPVmNitbnyUoR97tq8hXh5xfy";

        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches(password, hash),
            "Seed hash for 'jana.novakova' must verify against BCryptPasswordEncoder"
        );
    }

    @Test
    void validateIvka123Hash() {
        String password = "ivka123";
        String hash = "$2a$10$4zCsCZ29WwEFxJr6/1DmEeWR.pMMRDzb4ixRtF15u3QPE5W4Gku.y";

        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches(password, hash),
            "Seed hash for 'ivka' must verify against BCryptPasswordEncoder"
        );
    }

    @Test
    void generateNewHashes() {
        String[] passwords = {"admin123", "password123", "ivka123"};

        System.out.println("\n=== Generating new BCrypt hashes (cost factor 10) ===\n");
        for (String password : passwords) {
            String hash = encoder.encode(password);
            System.out.println("Password: " + password);
            System.out.println("Hash:     " + hash);
            System.out.println();
        }
        System.out.println("Use these hashes to update V3__seed_users_and_races.sql");
    }

    // ---- V5 seed users (generated by backend/scripts/build_seed_sql.py) ----

    @Test
    void validate_petr_svoboda_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("heslo2026", "$2b$10$YTr8Q/U9DFaYpjORTdGZIepDHpC8Q95NL5diVy62n/28i3lFhQE8y"),
            "V5 seed hash for petr.svoboda must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_martina_dvorakova_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("runner2026", "$2b$10$luvFdgZ1UFR//Y1/ObcdcuNZDjfWUr5xNbrS/MUSEW6z0Vtbb6kO6"),
            "V5 seed hash for martina.dvorakova must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_tomas_cerny_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("sportak42", "$2b$10$seKGfy3oSwtI7spsXndKduIvrwTOM9OhF0s6Dm5S0cdfvsbpKilES"),
            "V5 seed hash for tomas.cerny must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_katerina_prochazkova_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("bezec2026", "$2b$10$.U0H5SxUHlhYMa/e46/z/eG32H93Kf9h4ArsR3qXx2e1xcZe4Vo72"),
            "V5 seed hash for katerina.prochazkova must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_jakub_kucera_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("kucera2026", "$2b$10$7WlbubMmEgPN9Jo8KBw8UuGqSVNtCvymk0ygMQ0zZ6K7BoZVbomzS"),
            "V5 seed hash for jakub.kucera must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_lucie_vesela_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("lucie2026", "$2b$10$F.GRV0dt1lY.AlS7wfkR7.DhkkDxSOIn6cWHZrdJrYY/bauuc9CQy"),
            "V5 seed hash for lucie.vesela must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_david_horak_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("horak2026", "$2b$10$5kqHAK3lojbhBY3wkkwxaOwH0heOl.H6ooAJxhO3AZeELIviBQvqG"),
            "V5 seed hash for david.horak must verify against BCryptPasswordEncoder");
    }

    @Test
    void validate_eva_benesova_Hash() {
        org.junit.jupiter.api.Assertions.assertTrue(
            encoder.matches("benesova26", "$2b$10$rmmcYm5YEZCFjobsjNwIv.WyGDurKpdYGXVLsONIa8j3Hp3oe5iO."),
            "V5 seed hash for eva.benesova must verify against BCryptPasswordEncoder");
    }
}
